### ISSUE TITLE
Unable to download specific anime

### ISSUE THREAD

**Issue by ventrelo** [Zethu5/Anime-Downloader#3]
Hello,

I'm unable to download the new Nier automata anime.
Site: tokyo
Provider: Erai-raws
Anime: NieR-Automata Ver1. 1a - 02 [1080p]

Probably special characters issue.

**Comment by Zethu5** [comment]
"NieR-Automata Ver1. 1a" written wrong, windows adds space when copy-pasting the title, remove the space, should be:

**Comment by Zethu5** [comment]
.... "NieR-Automata Ver1.1a - 1"

**Comment by Zethu5** [comment]
Closed
